name: mqpal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.1
  googleapis: any
  googleapis_auth: any
  http: any
  google_sign_in: ^6.2.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  uuid: ^4.4.0
  cloud_firestore: ^5.6.5
  connectivity_plus: ^6.0.3
  responsive_framework: ^1.4.0
  sizer: ^3.0.5
  sqflite: ^2.4.2
  firebase_auth: ^5.5.1
  crypto: ^3.0.6
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  fonts: 
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/mq-campus-map.png